import React from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Container,
  Typography,
  Button,
  Grid,
  Card,
  CardContent,
  CardMedia,
  useTheme,
} from '@mui/material';
import {
  School,
  AutoStories,
  Psychology,
  Speed,
} from '@mui/icons-material';

const FeatureCard = ({ icon, title, description }) => (
  <Card
    sx={{
      height: '100%',
      background: 'rgba(30, 30, 30, 0.8)',
      backdropFilter: 'blur(10px)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      transition: 'transform 0.2s',
      '&:hover': {
        transform: 'translateY(-8px)',
      },
    }}
  >
    <CardContent>
      <Box
        sx={{
          display: 'flex',
          alignItems: 'center',
          mb: 2,
          color: 'primary.main',
        }}
      >
        {icon}
        <Typography variant="h6" sx={{ ml: 1 }}>
          {title}
        </Typography>
      </Box>
      <Typography variant="body2" color="text.secondary">
        {description}
      </Typography>
    </CardContent>
  </Card>
);

const HeroSection = () => {
  const theme = useTheme();
  const navigate = useNavigate();
  const isDark = theme.palette.mode === 'dark';

  return (
    <Box
      sx={{
        minHeight: '70vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: isDark
          ? 'linear-gradient(135deg, #23272F 0%, #181A20 100%)'
          : 'linear-gradient(135deg, #f5f7fa 0%, #e3e6ee 100%)',
        py: 8,
      }}
    >
      <Container maxWidth="md">
        <Typography
          variant="h2"
          sx={{
            fontWeight: 700,
            color: isDark ? 'primary.light' : 'primary.main',
            mb: 2,
            textAlign: 'center',
          }}
        >
          AI-Powered Course Generator
        </Typography>
        <Typography
          variant="h5"
          sx={{
            color: isDark ? 'text.secondary' : 'text.primary',
            mb: 4,
            textAlign: 'center',
          }}
        >
          Instantly create, customize, and manage courses with the power of AI. Switch between light and dark mode for your perfect learning experience.
        </Typography>
        <Box sx={{ display: 'flex', justifyContent: 'center' }}>
          <Button
            variant="contained"
            size="large"
            sx={{
              px: 5,
              py: 1.5,
              fontWeight: 600,
              fontSize: '1.2rem',
              background: 'linear-gradient(45deg, #7C4DFF 30%, #00E5FF 90%)',
              boxShadow: 3,
            }}
            onClick={() => navigate('/generate')}
          >
            Generate a Course
          </Button>
        </Box>
      </Container>
    </Box>
  );
};

const Home = () => {
  return (
    <>
      <HeroSection />
      {/* Features Section */}
      <Container maxWidth="lg" sx={{ py: 8 }}>
        <Typography
          variant="h3"
          component="h2"
          align="center"
          gutterBottom
          sx={{ mb: 6 }}
        >
          Why Choose Us?
        </Typography>
        <Grid container spacing={4}>
          <Grid item xs={12} sm={6} md={3}>
            <FeatureCard
              icon={<School sx={{ fontSize: 40 }} />}
              title="AI-Powered Learning"
              description="Get personalized course recommendations and content generated by advanced AI algorithms."
            />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <FeatureCard
              icon={<AutoStories sx={{ fontSize: 40 }} />}
              title="Rich Content"
              description="Access a vast library of courses and learning materials across various subjects."
            />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <FeatureCard
              icon={<Psychology sx={{ fontSize: 40 }} />}
              title="Smart Analytics"
              description="Track your progress and get insights to optimize your learning journey."
            />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <FeatureCard
              icon={<Speed sx={{ fontSize: 40 }} />}
              title="Fast Learning"
              description="Accelerate your learning with our efficient and engaging course structure."
            />
          </Grid>
        </Grid>
      </Container>
    </>
  );
};

export default Home; 