import React from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Container,
  Typography,
  Button,
  Grid,
  Card,
  CardContent,
  CardMedia,
} from '@mui/material';
import {
  School,
  AutoStories,
  Psychology,
  Speed,
} from '@mui/icons-material';

const FeatureCard = ({ icon, title, description }) => (
  <Card
    sx={{
      height: '100%',
      background: 'rgba(30, 30, 30, 0.8)',
      backdropFilter: 'blur(10px)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      transition: 'transform 0.2s',
      '&:hover': {
        transform: 'translateY(-8px)',
      },
    }}
  >
    <CardContent>
      <Box
        sx={{
          display: 'flex',
          alignItems: 'center',
          mb: 2,
          color: 'primary.main',
        }}
      >
        {icon}
        <Typography variant="h6" sx={{ ml: 1 }}>
          {title}
        </Typography>
      </Box>
      <Typography variant="body2" color="text.secondary">
        {description}
      </Typography>
    </CardContent>
  </Card>
);

const Home = () => {
  const navigate = useNavigate();

  return (
    <Box
      sx={{
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #1E1E1E 0%, #2D2D2D 100%)',
      }}
    >
      {/* Hero Section */}
      <Box
        sx={{
          pt: 8,
          pb: 6,
          background: 'linear-gradient(45deg, rgba(124, 77, 255, 0.1) 30%, rgba(0, 229, 255, 0.1) 90%)',
        }}
      >
        <Container maxWidth="lg">
          <Grid container spacing={4} alignItems="center">
            <Grid item xs={12} md={6}>
              <Typography
                variant="h2"
                component="h1"
                gutterBottom
                sx={{
                  fontWeight: 700,
                  background: 'linear-gradient(45deg, #7C4DFF 30%, #00E5FF 90%)',
                  backgroundClip: 'text',
                  textFillColor: 'transparent',
                }}
              >
                Learn Smarter with AI
              </Typography>
              <Typography variant="h5" color="text.secondary" paragraph>
                Generate personalized courses and accelerate your learning journey with our AI-powered platform.
              </Typography>
              <Box sx={{ mt: 4 }}>
                <Button
                  variant="contained"
                  size="large"
                  onClick={() => navigate('/register')}
                  sx={{
                    mr: 2,
                    mb: 2,
                    background: 'linear-gradient(45deg, #7C4DFF 30%, #00E5FF 90%)',
                    '&:hover': {
                      background: 'linear-gradient(45deg, #6B3FE7 30%, #00CCE5 90%)',
                    },
                  }}
                >
                  Get Started
                </Button>
                <Button
                  variant="outlined"
                  size="large"
                  onClick={() => navigate('/login')}
                  sx={{ mb: 2 }}
                >
                  Sign In
                </Button>
              </Box>
            </Grid>
            <Grid item xs={12} md={6}>
              <CardMedia
                component="img"
                image="/hero-image.png"
                alt="AI Learning"
                sx={{
                  borderRadius: 4,
                  boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
                }}
              />
            </Grid>
          </Grid>
        </Container>
      </Box>

      {/* Features Section */}
      <Container maxWidth="lg" sx={{ py: 8 }}>
        <Typography
          variant="h3"
          component="h2"
          align="center"
          gutterBottom
          sx={{ mb: 6 }}
        >
          Why Choose Us?
        </Typography>
        <Grid container spacing={4}>
          <Grid item xs={12} sm={6} md={3}>
            <FeatureCard
              icon={<School sx={{ fontSize: 40 }} />}
              title="AI-Powered Learning"
              description="Get personalized course recommendations and content generated by advanced AI algorithms."
            />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <FeatureCard
              icon={<AutoStories sx={{ fontSize: 40 }} />}
              title="Rich Content"
              description="Access a vast library of courses and learning materials across various subjects."
            />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <FeatureCard
              icon={<Psychology sx={{ fontSize: 40 }} />}
              title="Smart Analytics"
              description="Track your progress and get insights to optimize your learning journey."
            />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <FeatureCard
              icon={<Speed sx={{ fontSize: 40 }} />}
              title="Fast Learning"
              description="Accelerate your learning with our efficient and engaging course structure."
            />
          </Grid>
        </Grid>
      </Container>
    </Box>
  );
};

export default Home; 